<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>Agash</Authors>
    <Company>Agash</Company>
    <Copyright>Copyright © Agash</Copyright>
    <RepositoryUrl>https://github.com/Agash/StreamElements.Client</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <None
      Include="$(MSBuildThisFileDirectory)README.md"
      Pack="true"
      PackagePath="\"
      Visible="false"
    />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" PrivateAssets="all" />
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="all" />
  </ItemGroup>
</Project>
