<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageId>StreamElements.Client.DependencyInjection</PackageId>
    <Title>StreamElements.Client.DependencyInjection</Title>
    <Description>Microsoft.Extensions.DependencyInjection extensions for StreamElements.Client.</Description>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StreamElements.Client\StreamElements.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
</Project>
